### ISSUE TITLE
Does updateValue push changes to the associated Jamf server?

### ISSUE THREAD

**Issue by JacksonUtsch** [jamf/ManagedAppConfigLib#2]
I have a hosted app and basically have read capabilities with attribute extensions.

I'm looking to be able to write values from a managed app via its source code. I'm using this library and attempting to use **updateValue** to write a new value but I'm not seeing this take any effect to either "com.apple.feedback.managed" or "com.apple.configuration.managed". 

Is this the intended functionality of updateValue and am I miss-using it?

Thanks!

**Comment by KeplerKid** [comment]
Hi Jackson,

The updateValue function does not send any values to the MDM server. The only way that happens is via the Collect Feedback MDM command (not sure if that’s the exact name) which will read, and optionally clear depending on the setting in the command, the contends of the feedback dictionary.

________________________________
From: Jackson Utsch ***@***.***>
Sent: Thursday, May 13, 2021 2:06:14 PM
To: jamf/ManagedAppConfigLib ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jamf/ManagedAppConfigLib] Does updateValue push changes to the associated Jamf server? (#2)


I have a hosted app and basically have read capabilities with attribute extensions.

I'm looking to be able to write values from a managed app via its source code. I'm using this library and attempting to use updateValue to write a new value but I'm not seeing this take any effect to either "com.apple.feedback.managed" or "com.apple.configuration.managed".

Is this the intended functionality of updateValue and am I miss-using it?

Thanks!

**Comment by JacksonUtsch** [comment]
Hey, thanks for the response. 

Is this what you are talking about? https://developer.apple.com/documentation/devicemanagement/get_app_feedback
It looks like it is a server(Jamf/MDM) facing item. Is there existing support to be able to call or utilize this?

**Comment by JacksonUtsch** [comment]
I believe that it would be listed here: https://docs.jamf.com/10.29.0/jamf-pro/administrator-guide/Remote_Commands_for_Mobile_Devices.html

But not seeing it. Just hoping to get pointed in the right direction so I can get write capabilities 😃

**Comment by KeplerKid** [comment]
Yes, that’s the command. Jamf Pro does not currently support that command. I’m not sure what other MDMs do.


________________________________
